name: Run script on push to directory task2_srv

on:
  push:
    paths:
      - task2_srv/**

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make task2_srv executable
      run: chmod +x ./.github/task2_srv

    - name: Running task2_srv script
      run: |
        echo 'Running script task2_srv ...'
        ./.github/task2_srv > result-task2_srv.log
        cat result-task2_srv.log

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result-task2_srv.log
