name: Run script on push to directory task1_vsn

on:
  push:
    paths:
      - task1_vsn/**

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make task1_vsn executable
      run: chmod +x ./.github/task1_vsn

    - name: Running task1_vsn script
      run: |
        echo 'Running script task1_vsn ...'
        ./.github/task1_vsn > result-task1_vsn.log
        cat result-task1_vsn.log

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result-task1_vsn.log
