name: Run script on push to directory task5_mob

on:
  push:
    paths:
      - task5_mob/**

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make task5_mob executable
      run: chmod +x ./.github/task5_mob

    - name: Running task5_mob script
      run: |
        echo 'Running script task5_mob ...'
        ./.github/task5_mob > result-task5_mob.log
        cat result-task5_mob.log

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: result-task5_mob.log
